export interface LibraryEntry {
  id: string;
  title: string;
  source: string;
  level: "beginner" | "intermediate" | "advanced";
  description: string;
  paragraphs: string[];
}

export const LIBRARY_CONTENT: LibraryEntry[] = [
  {
    id: "voa-simple-english-1",
    title: "What Is Climate Change?",
    source: "VOA Learning English (adapted)",
    level: "beginner",
    description:
      "Learn about climate change in simple English. Great for beginners.",
    paragraphs: [
      "Climate change refers to long-term shifts in temperatures and weather patterns.",
      "These shifts may be natural, such as through variations in the solar cycle.",
      "But since the 1800s, human activities have been the main driver of climate change.",
      "This is primarily due to burning fossil fuels like coal, oil, and gas.",
      "Burning fossil fuels generates greenhouse gas emissions.",
      "These emissions act like a blanket wrapped around the Earth.",
      "They trap the sun's heat and raise temperatures.",
      "The Earth is now about 1.1 degrees Celsius warmer than in the late 1800s.",
      "The last decade was the warmest on record.",
      "Many people think climate change mainly means warmer temperatures.",
      "But temperature rise is only the beginning of the story.",
      "Because the Earth is a system, where everything is connected, changes in one area can influence changes in all others.",
      "The consequences of climate change now include intense droughts, water scarcity, severe fires, rising sea levels, flooding, melting polar ice, catastrophic storms, and declining biodiversity.",
    ],
  },
  {
    id: "voa-simple-english-2",
    title: "The History of the Internet",
    source: "VOA Learning English (adapted)",
    level: "beginner",
    description:
      "A brief history of the internet, from its military origins to the modern web.",
    paragraphs: [
      "The internet began as a United States military project in the late 1960s.",
      "It was called ARPANET, which stands for Advanced Research Projects Agency Network.",
      "The goal was to create a communication network that could survive a nuclear attack.",
      "In the 1970s, scientists developed a way for different computer networks to communicate with each other.",
      "This technology was called TCP/IP, and it became the foundation of the modern internet.",
      "In 1991, a British scientist named Tim Berners-Lee invented the World Wide Web.",
      "The Web made it easy for people to share information using web pages and links.",
      "By the mid-1990s, millions of people around the world were using the internet.",
      "Companies like Amazon, Google, and Yahoo were founded during this time.",
      "Today, more than five billion people use the internet every day.",
      "The internet has changed how we work, learn, shop, and communicate.",
      "It has made the world a more connected place.",
    ],
  },
  {
    id: "voa-simple-english-3",
    title: "How Sleep Affects Your Health",
    source: "VOA Learning English (adapted)",
    level: "beginner",
    description:
      "Learn why sleep is important for your body and mind.",
    paragraphs: [
      "Sleep is one of the most important things you can do for your health.",
      "Most adults need seven to nine hours of sleep each night.",
      "Children and teenagers need even more sleep than adults.",
      "When you sleep, your body repairs itself.",
      "Your brain forms new pathways to help you learn and remember information.",
      "Studies show that a good night's sleep improves learning.",
      "Whether you are learning math, how to play the piano, or how to drive a car, sleep helps improve your skills.",
      "Sleep also affects your mood.",
      "People who do not get enough sleep are more likely to feel sad, angry, or stressed.",
      "Lack of sleep has been linked to depression and other mental health problems.",
      "Your immune system also depends on sleep.",
      "Ongoing sleep deficiency can change the way your immune system responds.",
      "If you are sleep deficient, you may have trouble fighting common infections.",
      "To improve your sleep, try to go to bed and wake up at the same time every day.",
      "Avoid bright screens for one hour before bedtime.",
      "Make your bedroom cool, dark, and quiet.",
    ],
  },
  {
    id: "ted-style-1",
    title: "The Power of Introverts",
    source: "Public domain educational content",
    level: "intermediate",
    description:
      "Exploring why introverts are undervalued in modern society and how they contribute uniquely.",
    paragraphs: [
      "In a culture where being social and outgoing is prized above all else, it can be difficult, even shameful, to be an introvert.",
      "But introverts bring extraordinary talents and abilities to the world, and should be encouraged and celebrated.",
      "One third to one half of the population are introverts.",
      "That means one out of every two or three people you know is an introvert.",
      "Introverts prefer less stimulating environments and tend to enjoy quiet concentration.",
      "They listen more than they talk, think before they speak, and often feel as if they express themselves better in writing than in conversation.",
      "Many of the world's most creative and influential people were introverts.",
      "Albert Einstein, Rosa Parks, Eleanor Roosevelt, and Mahatma Gandhi all described themselves as quiet or soft-spoken people.",
      "The key to maximizing our talents is for everyone to be placed in the zone of stimulation that is right for them.",
      "Schools and workplaces should create more privacy, more freedom, and more autonomy.",
      "When it comes to creativity and leadership, we need introverts doing what they do best.",
      "Solitude matters, and for some people, it is the air that they breathe.",
    ],
  },
  {
    id: "science-1",
    title: "How Vaccines Work",
    source: "Public domain science content",
    level: "intermediate",
    description:
      "Understanding the science behind vaccines and how they protect us from diseases.",
    paragraphs: [
      "Vaccines are one of the most important medical inventions in human history.",
      "They have saved millions of lives by preventing deadly diseases.",
      "A vaccine works by teaching your immune system to recognize and fight a specific virus or bacteria.",
      "Most vaccines contain a weakened or inactive form of the germ that causes a disease.",
      "When the vaccine enters your body, your immune system detects these foreign substances.",
      "Your body then produces antibodies, which are special proteins designed to fight that specific germ.",
      "After vaccination, your immune system remembers the germ.",
      "If you encounter the real virus or bacteria later, your body can fight it off quickly.",
      "This is called immunity.",
      "Some vaccines require multiple doses to build full protection.",
      "Booster shots may be needed over time because immunity can decrease.",
      "When enough people in a community are vaccinated, it becomes difficult for diseases to spread.",
      "This concept is called herd immunity.",
      "Herd immunity is especially important for protecting people who cannot be vaccinated, such as newborns or people with certain health conditions.",
      "Vaccines go through rigorous testing before they are approved for public use.",
      "Scientists conduct clinical trials that can take many years to ensure vaccines are safe and effective.",
    ],
  },
  {
    id: "business-1",
    title: "The Art of Effective Communication",
    source: "Public domain business content",
    level: "intermediate",
    description:
      "Essential communication skills for professional and personal success.",
    paragraphs: [
      "Effective communication is one of the most valuable skills you can develop.",
      "Whether you are giving a presentation, writing an email, or having a conversation, clear communication is essential.",
      "The first rule of effective communication is to know your audience.",
      "Before you speak or write, consider who will receive your message and what they need to know.",
      "Active listening is just as important as speaking clearly.",
      "When someone is talking to you, give them your full attention.",
      "Do not interrupt or plan your response while they are still speaking.",
      "Instead, listen to understand, not just to reply.",
      "Body language plays a significant role in communication.",
      "Your facial expressions, gestures, and posture can reinforce or contradict your words.",
      "Maintaining eye contact shows confidence and engagement.",
      "In written communication, clarity and brevity are key.",
      "Use simple, direct language whenever possible.",
      "Avoid jargon unless you are certain your reader will understand it.",
      "Finally, always proofread your written messages before sending them.",
      "A small error can change the meaning of your message entirely.",
    ],
  },
  {
    id: "news-1",
    title: "The Rise of Artificial Intelligence",
    source: "Public domain technology content",
    level: "advanced",
    description:
      "How AI is transforming industries and what it means for the future.",
    paragraphs: [
      "Artificial intelligence has rapidly moved from the realm of science fiction to an integral part of everyday life.",
      "From virtual assistants on our smartphones to recommendation algorithms on streaming platforms, AI is everywhere.",
      "Machine learning, a subset of AI, allows computers to learn from data without being explicitly programmed.",
      "Deep learning, which uses neural networks inspired by the human brain, has enabled breakthroughs in image recognition, natural language processing, and game playing.",
      "In healthcare, AI systems can analyze medical images to detect diseases earlier and more accurately than human doctors in some cases.",
      "In finance, algorithms can process vast amounts of data to detect fraud and make investment decisions in milliseconds.",
      "However, the rapid advancement of AI also raises significant ethical concerns.",
      "Questions about job displacement, privacy, algorithmic bias, and the concentration of power in technology companies are being debated worldwide.",
      "Some experts worry about the development of artificial general intelligence, which would match or exceed human cognitive abilities across all domains.",
      "Others argue that such concerns are premature and that current AI systems are narrow in their capabilities.",
      "What is clear is that AI will continue to transform industries, economies, and societies for decades to come.",
      "Preparing for this future requires investment in education, thoughtful regulation, and inclusive dialogue about the kind of world we want to create.",
    ],
  },
  {
    id: "literature-1",
    title: "The Gift of the Magi (excerpt)",
    source: "O. Henry (Public Domain, 1905)",
    level: "advanced",
    description:
      "A classic short story about love and sacrifice during the holiday season.",
    paragraphs: [
      "One dollar and eighty-seven cents. That was all. And sixty cents of it was in pennies.",
      "Pennies saved one and two at a time by bulldozing the grocer and the vegetable man and the butcher until one's cheeks burned with the silent imputation of parsimony that such close dealing implied.",
      "Three times Della counted it. One dollar and eighty-seven cents. And the next day would be Christmas.",
      "There was clearly nothing to do but flop down on the shabby little couch and howl. So Della did it.",
      "While the mistress of the home is gradually subsiding from the first stage to the second, take a look at the home.",
      "A furnished flat at eight dollars per week. It did not exactly beggar description, but it certainly had that word on the lookout for the mendicancy squad.",
      "In the vestibule below was a letter-box into which no letter would go, and an electric button from which no mortal finger could coax a ring.",
      "Also appertaining thereunto was a card bearing the name Mister James Dillingham Young.",
      "Della finished her cry and attended to her cheeks with the powder rag.",
      "She stood by the window and looked out dully at a gray cat walking a gray fence in a gray backyard.",
      "Tomorrow would be Christmas Day, and she had only one dollar and eighty-seven cents with which to buy Jim a present.",
      "She had been saving every penny she could for months, with this result.",
    ],
  },
];
